BDCAT preprod 2020.11 release 2020.11 preprod.gen3.biodatacatalyst.nhlbi.nih.gov 1604000217
uc-cdis/cdis-manifest pull request #2277
Opened 2020-10-29 19:37 UTC by themarcelor

Applying version 2020.11 to preprod.gen3.biodatacatalyst.nhlbi.nih.gov

2020-11-03 15:49 UTC, Avantol13 approved these changes

2020-11-03 16:08 UTC, mpingram requested changes
Ok to downgrade from arborist 2.5.0 to 2020.11? (See comment)

2020-11-05 17:33 UTC, themarcelor commented on preprod.gen3.biodatacatalyst.nhlbi.nih.gov/manifest.json
> -    "arborist": "707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/arborist:2.5.0",
We took care of that.
https://github.com/uc-cdis/arborist/commits/2020.11
11:33
Fix anonymous authz bug (#124)
paulineribeyre authored and Marcelo Costa committed 15 days ago
c124786

2020-11-05 17:41 UTC, mpingram approved these changes

2020-11-05 19:06 UTC, ac3eb approved these changes

2020-11-05 19:07 UTC, merged