BDCat Feb 2021 prod release 1613594420
uc-cdis/cdis-manifest pull request #2628
Opened 2021-02-17 20:40 UTC by themarcelor

copying files from preprod.gen3.biodatacatalyst.nhlbi.nih.gov to gen3.biodatacatalyst.nhlbi.nih.gov

2021-02-17 22:38 UTC, Avantol13 requested changes

2021-02-17 22:38 UTC, Avantol13 commented on gen3.biodatacatalyst.nhlbi.nih.gov/manifest.json
> +    "dictionary_url": "https://s3.amazonaws.com/dictionary-artifacts/gtexdictionary/4.0.4/schema.json",
:warning: We do not want to update this if we're not doing a data release

2021-03-02 19:16 UTC, emalinowski approved these changes

2021-03-02 19:30 UTC, Avantol13 commented on gen3.biodatacatalyst.nhlbi.nih.gov/manifest.json
> +    "dictionary_url": "https://s3.amazonaws.com/dictionary-artifacts/gtexdictionary/4.0.4/schema.json",
we are doing a data release. so we want this

2021-03-02 19:30 UTC, Avantol13 approved these changes

2021-03-02 19:38 UTC, merged