HEAL Prod - sync with pre-prod
uc-cdis/cdis-manifest pull request #3617
Opened 2021-10-08 13:40 UTC by haraprasadj

Link to Jira ticket if there is one:

### Environments

### Description of changes

2021-10-08 13:42 UTC, mfshao requested changes
Don't update anything related to workspace now. Haven't finished testing preprod

2021-10-08 13:45 UTC, haraprasadj commented
> Don't update anything related to workspace now. Haven't finished testing preprod

Ok, let me make this one a draft PR and we can merge it once we are confident

2021-10-08 18:09 UTC, PlanXCyborg commented
# healdata.org/manifest.json
## :warning: Services on branch
- hatchery

2021-10-15 14:37 UTC, mfshao approved these changes

2021-10-18 15:00 UTC, merged