Readding images ommitted to staging. Revised based on edits requested.
uc-cdis/cdis-manifest pull request #5163
Opened 2022-09-26 16:56 UTC by DanBiber

Link to Jira ticket if there is one:

### Environments

### Description of changes

2022-09-26 17:00 UTC, swatkatsrazor approved these changes

2022-09-26 17:15 UTC, jmontmaxwell requested changes
- typo on line 522 "Users can click the link* ..."
- Missing space between first and second sentence in line 470.
- In line 470 consider "To start exploring BRH Workspaces right away users can apply for a temporary trial access to BRH workspaces, or more permanent access to BRH workspaces using NIH STRIDES."

2022-09-27 13:33 UTC, aartivnkt reviewed
LGTM. We can merge this after the jenkins build passes

2022-09-27 22:04 UTC, aartivnkt reviewed
Looks great Dan! I have one request:
In `Access to individual Studies` would it be possible to add  a new sentence after this one: `If you have access, a green box will show "You have access to this study"`.  The new sentence is `If you have access but cannot select the study to export to workspace, it is because the manifest is not yet available. Please use API for these cases`

2022-09-28 21:57 UTC, swatkatsrazor approved these changes

2022-09-28 21:59 UTC, jmontmaxwell approved these changes

2022-09-28 22:06 UTC, merged