Updating Env nci-crdc.datacommons.io - 2022.09 1664556619
uc-cdis/cdis-manifest pull request #5180
Opened 2022-09-30 16:50 UTC by PlanXCyborg

Applying version 2022.09 to nci-crdc.datacommons.io

2022-09-30 16:56 UTC, PlanXCyborg commented
# nci-crdc.datacommons.io/manifest.json
## Deployment changes
- metadata
  - Database migration for MDS (uc-cdis/metadata-service#63)
## Breaking changes
- indexd
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (uc-cdis/indexd#336)
- portal
  - Replaced loading  the data in  `iframes` in Workspace page with Redirect component. (uc-cdis/data-portal#1067)
  - Deprecating the use of `default-workspaces` i. e an individual commons will no longer be able to deploy standalone jupyterhub images, they may use [hatchery service](https://github.com/uc-cdis/hatchery) instead. (uc-cdis/data-portal#1067)
  - `studyRegistrationConfig` in `gitops.json` must now be placed within the `regsitrationConfigs.features` block [[Refer this PR](https://github.com/uc-cdis/cdis-manifest/pull/5095)] (uc-cdis/data-portal#1067)

2022-09-30 17:09 UTC, trevars requested changes

2022-09-30 17:09 UTC, trevars commented on nci-crdc.datacommons.io/manifest.json
> +    "fence": "707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/fence:2022.09",
I believe we still want fence:6.1.1. That's what we have in staging.

2022-09-30 18:22 UTC, trevars approved these changes

2022-10-03 16:34 UTC, PlanXCyborg commented
# nci-crdc.datacommons.io/manifest.json
## Deployment changes
- metadata
  - Database migration for MDS (uc-cdis/metadata-service#63)
## Breaking changes
- indexd
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (uc-cdis/indexd#336)
- portal
  - Replaced loading  the data in  `iframes` in Workspace page with Redirect component. (uc-cdis/data-portal#1067)
  - Deprecating the use of `default-workspaces` i. e an individual commons will no longer be able to deploy standalone jupyterhub images, they may use [hatchery service](https://github.com/uc-cdis/hatchery) instead. (uc-cdis/data-portal#1067)
  - `studyRegistrationConfig` in `gitops.json` must now be placed within the `regsitrationConfigs.features` block [[Refer this PR](https://github.com/uc-cdis/cdis-manifest/pull/5095)] (uc-cdis/data-portal#1067)

2022-10-03 23:42 UTC, PlanXCyborg commented
# nci-crdc.datacommons.io/manifest.json
## Deployment changes
- metadata
  - Database migration for MDS (uc-cdis/metadata-service#63)
## Breaking changes
- indexd
  - Ensure you are using Fence>=2021.10. Remove deprecated GA4GH access endpoints. these have existed (and been used) from the Fence microservice since last year. See cloud automation change [here](https://github.com/uc-cdis/cloud-automation/blob/f10f04f7957eb2ba179504f7df9d6429f7298835/gen3/bin/kube-setup-revproxy.sh#L78-L79) (uc-cdis/indexd#336)
- portal
  - Replaced loading  the data in  `iframes` in Workspace page with Redirect component. (uc-cdis/data-portal#1067)
  - Deprecating the use of `default-workspaces` i. e an individual commons will no longer be able to deploy standalone jupyterhub images, they may use [hatchery service](https://github.com/uc-cdis/hatchery) instead. (uc-cdis/data-portal#1067)
  - `studyRegistrationConfig` in `gitops.json` must now be placed within the `regsitrationConfigs.features` block [[Refer this PR](https://github.com/uc-cdis/cdis-manifest/pull/5095)] (uc-cdis/data-portal#1067)

2022-10-05 14:44 UTC, merged