Remove duplicate props
uc-cdis/cdis-manifest pull request #5235
Opened 2022-10-13 16:53 UTC by haraprasadj

project_id appears in two places which breaks the new ETL process

Link to Jira ticket if there is one:

### Environments

### Description of changes

2022-10-13 17:40 UTC, SpencerAxelrod approved these changes

2022-10-13 21:32 UTC, paulineribeyre requested changes
pretty sure the Anvil team would want to deploy this to their lower tier environments first and test it

2022-10-14 02:10 UTC, haraprasadj commented
> pretty sure the Anvil team would want to deploy this to their lower tier environments first and test it

Good point, I submitted a gitops-qa PR (https://github.com/uc-cdis/gitops-qa/pull/2230). @SpencerAxelrod can you please get these merged whenever ready?

2022-10-24 21:50 UTC, paulineribeyre approved these changes
removing my request for changes to unblock the PR, but note that this issue is still in the ETL mapping in AnVIL QA, internalstaging and staging so it has not been tested. Deferring to the AnVIL team

2022-10-25 14:43 UTC, merged