Gen3 Monthly Release 2024.02 validate.midrc.org 1706653391
uc-cdis/cdis-manifest pull request #6987
Opened 2024-01-30 22:23 UTC by PlanXCyborg

Applying version 2024.02 to validate.midrc.org

2024-02-12 19:35 UTC, paulineribeyre approved these changes

2024-02-12 19:39 UTC, frankliuao requested changes

2024-02-12 19:39 UTC, frankliuao commented on validate.midrc.org/manifest.json
> +    "tube": "707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/tube:2024.02",
This should be kept at 1.0.1?

2024-02-13 18:36 UTC, paulineribeyre approved these changes

2024-02-13 18:36 UTC, merged