configure hatchery for nextflow workspaces
uc-cdis/cdis-manifest pull request #7052
Opened 2024-02-09 18:45 UTC by jmontmaxwell

Link to Jira ticket if there is one:

### Environments
BRH Staging

### Description of changes

- Update hatchery config to remove old nextflow workspace and add the two enxtflow workspace from QA BRH
- Update manifest.json config for hatchery 2.0.1

2024-02-09 18:46 UTC, aartivnkt commented on brhstaging.data-commons.org/manifests/hatchery/hatchery.json
> +        "FRAME_ANCESTORS": "https://qa-brh.planx-pla.net"
this one is still `brhstaging` right?

2024-02-09 18:48 UTC, aartivnkt commented on brhstaging.data-commons.org/manifests/hatchery/hatchery.json
> +        "FRAME_ANCESTORS": "https://qa-brh.planx-pla.net"
same with above, change to `brhstaging`

2024-02-09 18:50 UTC, aartivnkt requested changes
left a couple of comments

2024-02-09 21:38 UTC, jmontmaxwell commented on brhstaging.data-commons.org/manifests/hatchery/hatchery.json
> +        "FRAME_ANCESTORS": "https://qa-brh.planx-pla.net"
fixed

2024-02-09 22:30 UTC, aartivnkt submitted a review, later dismissed

2024-02-12 15:20 UTC, paulineribeyre approved these changes

2024-02-12 16:31 UTC, merged