Switch off maintenance mode and banner
uc-cdis/cdis-manifest pull request #7537
Opened 2024-06-24 18:26 UTC by vzpgb

Link to Jira ticket if there is one:

### Environments
* va.data-commons.org

### Description of changes
* Disable maintenance mode and banner

2024-06-24 18:35 UTC, nmetokishlubsky submitted a review, later dismissed

2024-06-25 19:19 UTC, pieterlukasse requested changes

2024-06-25 19:19 UTC, pieterlukasse commented on va.data-commons.org/manifest.json
this file is outdated!

2024-06-25 19:22 UTC, pieterlukasse approved these changes

2024-06-25 19:30 UTC, merged