Gen3 Monthly Release 2024.09 gen3.theanvil.io 1725380453
uc-cdis/cdis-manifest pull request #7835
Opened 2024-09-03 16:21 UTC by PlanXCyborg

Applying version 2024.09 to gen3.theanvil.io

2024-09-03 21:43 UTC, k-burt-uch requested changes

2024-09-03 21:43 UTC, k-burt-uch commented on gen3.theanvil.io/manifest.json
> +    "portal": "707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/data-portal:2024.09",
```suggestion
    "portal": "707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/data-portal:5.33.1",
```

2024-09-03 21:43 UTC, k-burt-uch commented on gen3.theanvil.io/manifest.json
> +    "guppy": "707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/guppy:2024.09",
```suggestion
    "guppy": "707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/guppy:0.19.0",
```

2024-09-04 20:14 UTC, AlbertSnows commented
closing as anvil will no longer be used after this month

2024-09-05 16:27 UTC, merged